# Generated by Django 4.2.7 on 2025-05-29 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Imagen de Galería', 'verbose_name_plural': 'Imágenes de Galería'},
        ),
    ]
