# Generated by Django 4.2.7 on 2025-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_category_options_alter_galleryimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.ManyToManyField(related_name='gallery_images', to='content.category', verbose_name='Categoría'),
        ),
    ]
