# Generated by Django 4.2.7 on 2025-06-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_galleryimage_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='category',
            new_name='categories',
        ),
    ]
